export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const FETCH_SCREENPLAYS_START = 'FETCH_SCREENPLAYS_START';
export const FETCH_SCREENPLAYS_SUCCESS = 'FETCH_SCREENPLAYS_SUCCESS';
export const FETCH_SCREENPLAYS_FAIL = 'FETCH_SCREENPLAYS_FAIL';
export const SET_SCREENPLAYS = 'SET_SCREENPLAYS';

export const UPDATE_SCREENPLAY_START = 'UPDATE_SCREENPLAY_START';
export const UPDATE_SCREENPLAY_SUCCESS = 'UPDATE_SCREENPLAY_SUCCESS';
export const UPDATE_SCREENPLAY_FAIL = 'UPDATE_SCREENPLAY_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';